### PR TITLE
Assignment 2

### PR DESCRIPTION
**Pull request by RuiQianSun**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
I am adding code to load csv files, calculate summary statistics, and check for errors.

## What did you learn from the changes you have made?
I learned how to perform operations on arrays such as max, min, and mean

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I did not have any other approaches in mind for this assignment.

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
No major challenges, just had to read all the instructions carefully.

## How were these changes tested?
I tested additional print statements to check for zeros, I also took the min of the mean array to double-check for zeros.

## A reference to a related issue in your repository (if applicable)
No issues

## Checklist
- [X] I can confirm that my changes are working as intended

### CODE REVIEW

**Review by anjali-deshpande-hub — CHANGES_REQUESTED** [review]
Well done! Just one thing: I noticed that assignment_1.ipynb has also changed as part of this pull request. Only assignment_2.ipynb should have the required changes.

**Comment by RuiQianSun** [comment]
I see, I'm actually not sure why this happened or how to fix this.
Should I close this pull request and create another?

Best,
Rui Qian

________________________________

**Comment by anjali-deshpande-hub** [comment]
Please don't close the PR. You can continue to make review changes to the same branch and they will be reflected in this PR. 

You could have created the new branch from assignment-1 branch instead of from main. Another reason for this could be use of 'git add -A' command instead of specifying the file name. 

Refer to https://uoft-dsi-certificates.slack.com/archives/C080M1JFJ8G/p1733888574840979 for correct it.

**Comment by RuiQianSun** [comment]
> Please don't close the PR. You can continue to make review changes to the same branch and they will be reflected in this PR.
> 
> You could have created the new branch from assignment-1 branch instead of from main. Another reason for this could be use of 'git add -A' command instead of specifying the file name.
> 
> Refer to https://uoft-dsi-certificates.slack.com/archives/C080M1JFJ8G/p1733888574840979 for correct it.

Understood, I'll fix this pull request tonight

**Comment by RuiQianSun** [comment]
Hello,

I've made the corrections to the pull request, please let me know when I can close the pull request.

Best,
Rui Qian

________________________________

**Review by anjali-deshpande-hub — APPROVED** [review]
Well done! Its fixed now.

**Pull request closed without merging**
